### PR TITLE
Include a link to the player's chapter on the member detail page.

### LINKED ISSUE #106: Provide a link to the member's chapter on their detail page
## Is your feature request related to a problem?
Not specifically.

## Describe the feature you'd like to see on the AGAGD.
A "chapter" field on the user's player card, with the chapter name hyperlinked to the chapter detail page.

### PR DESCRIPTION
**Pull request by annabunches**
This won't work (and probably shouldn't be merged) until after #93 is closed. It could also stand to wait until #120 so local testing can be applied.

Fixes #106

### CODE REVIEW

**Comment by EarthSchlange** [comment]
Looks good, but I do agree we need to wait on those other issues #93 and #120 and for local testing

**Comment by annabunches** [comment]
For reference here are before and after images. Feel free to critique the placement of the chapter info, I can fine tune that if you think there's a better spot.

chapter_link_before
chapter_link_after

**Comment by vash3g** [comment]
Thoughts on changing the order of the list on the left:

Current Way | New Way
-----------------|---------------
member since | rating
expiration  | expiration
member type | chapter
chapter | member since
rating | member type
highest rating | highest rating
sigma | sigma
last rated at | last tournament
last tournament | last rated at

**Comment by EarthSchlange** [comment]
I would look at something more like this:

Current | New
-- | --
Member Since | Rating
Expiration Date | Highest Rating
Membership Type | Sigma
Rating | Last Rated At
Highest Rating | Last Tournament
Sigma | Membership Type
Last Rated At | Member Since
Last Tournament | Expiration Date

**Comment by annabunches** [comment]
Here's my current proposal for re-ordering, based on comments here and in the dev meeting.

Reasoning is as follows:

* As a *user*, I'm most likely to want to know how strong a player is (rating) and where this player plays (chapter). Membership & expiration info gives me a sense of how long they've been playing (with the AGA at least) and whether they are nominally active,  and of course is useful for TDs. "Membership type" is included there just to keep like data closer together. The data toward the end is, of course, still potentially interesting (otherwise why include it at all?) but slightly less likely to be what someone is looking for.

Screenshot 2020-10-11 170045

**Review by EarthSchlange — COMMENTED** [review]
I'm running into a bit of an error running this and I am using the same data as in #125.
image

Running with on #125:
image

**Comment by annabunches** [comment]
Hm. I don't see any *error* in that output, looks like it is in the middle of the stack trace. Can you capture the nominal error?

**Comment by annabunches** [comment]
Ah, I was able to reproduce the error I think. It worked *before* your latest changes to #125 - I hadn't re-generated my data from that PR in some time.

It actually appears to be a new error introduced into #125. Here's some SQL queries that demonstrate the problem:

```
mysql> select chapter_id from members where member_id = 44;
+------------+
| chapter_id |
+------------+
|          5 |
+------------+

mysql> select member_id from chapters;                                                                                                                 
+-----------+
| member_id |                                                                                                                                           +-----------+
|       102 |                                                                                                                                           |       103 |
|       104 |                                                                                                                                           |       105 |
|       106 |                                                                                                                                           +-----------+

```

The fake fixtures script is no longer mapping the users to the chapters correctly.

This DOES expose a flaw in this PR though - we should handle the case where the chapter ID doesn't exist. (notably, we have data in prod where `chapter_id = 0`, so this is important)

**Comment by annabunches** [comment]
Latest code should work, even with the broken fixture data. PTAL. :)

**Review by EarthSchlange — APPROVED** [review]
Looks good.
image

**Comment by EarthSchlange** [comment]
Yeah, I think I was overzealous with the chapter id move. 

https://github.com/usgo/agagd/blob/2559e73bfff75eab0101b34396875088eceea643/scripts/make_fake_fixtures.py#L171

> It actually appears to be a new error introduced into #125. Here's some SQL queries that demonstrate the problem:
> 
> ```
> mysql> select chapter_id from members where member_id = 44;
> +------------+
> | chapter_id |
> +------------+
> |          5 |
> +------------+
> 
> mysql> select member_id from chapters;                                                                                                                 
> +-----------+
> | member_id |                                                                                                                                           +-----------+
> |       102 |                                                                                                                                           |       103 |
> |       104 |                                                                                                                                           |       105 |
> |       106 |                                                                                                                                           +-----------+
> ```
> 
> The fake fixtures script is no longer mapping the users to the chapters correctly.

**Comment by EarthSchlange** [comment]
Works fine with update in as of update #107.

**Pull request merged**
