### PR TITLE
Add missing rating information to the chapter and country pages.

### LINKED ISSUE #134: Ratings don't appear on Chapter page
## Summary of the Bug
The rating column in the chapter view is always just `—`, even when players have ratings.

E.g. compare https://agagd.usgo.org/chapter/NOVA/ with https://agagd.usgo.org/search/?q=Aarhus.

## Steps to Reproduce the Behaviour
1. Go to the links above.

## The Expected Behaviour
Ratings should be populated on the chapter member table as well as other views.

### PR DESCRIPTION
**Pull request by annabunches**
Fixes #134

### CODE REVIEW

**Review by EarthSchlange — CHANGES_REQUESTED** [review]
The changes here seem to break both of chapters pages and country in development.

**Comment by annabunches** [comment]
The change doesn't break the chapters, it just hasn't merged those changes in yet. I'll merge master and push :)

**Comment by annabunches** [comment]
Well, I was right in that I don't see this issue in my testing. Screenshots of working chapters and country view, with ratings:
Screenshot 2020-10-16 161011
Screenshot 2020-10-16 160951

**Review by EarthSchlange — APPROVED** [review]
Looks good to me. I think this merged wrong initially. 
image

image

**Pull request merged**
